### ISSUE TITLE
Back button behavior inconsistency

### ISSUE THREAD

**Issue by end-4** [ExpidusOS/file-manager#1]
# The problem

- The Back button on the top left corner navigates to parent directory at first, but navigates to the previous screen instead of the parent directory after an entry is selected. This makes it impossible to go up a directory when browsing an entry on the sidebar.

- Video:
https://github.com/ExpidusOS/file-manager/assets/97237370/2ec72ee3-f64e-4489-ace2-52afc3d666d9

# Expected behavior

- The Back button should navigate to the parent directory, except when the current displaying directory is already the selected entry from the sidebar

**Comment by RossComputerGuy** [comment]
Ok, it should be fixed now.
